### ISSUE TITLE
Wheat cannot be replaced when placing block (unlike grass)

### ISSUE THREAD

**Issue by koneshnoVasya** [PrismarineJS/mineflayer-pathfinder#102]
seems like a bot treats a wheat like a grass (usually you can replace grass with another block, but not wheat)

https://user-images.githubusercontent.com/42637020/104086675-efe97e80-526a-11eb-877c-b1e18c26f55f.mp4

**Comment by Karang** [comment]
Solved. Update to 1.3.3

**Comment by koneshnoVasya** [comment]
thanks
