### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by Rob9315** [PrismarineJS/mineflayer-pathfinder#103]
when two bots move together in unison, and both try to place a block below them, each time they fail a new listener is added, which after some time crashes mineflayer. 

my possible fix ideas:
-  add a timeout to delete the listeners automatically after some time if they did not activate
- better entity check before placing a block
- option to avoid other entities (bots) when pathfinding

**Comment by Karang** [comment]
Pathfinder itself doesn't register events when placing blocks. It would be good to pin point which events exactly get added and report the issue to mineflayer.

For an option to avoid entities, it is planned but not trivial to implement.

**Comment by Rob9315** [comment]
ok, sounds reasonable, will do
