### ISSUE TITLE
Can not spam setGoal anymore

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#108]
Hi, when I spam the bot with a goalfollow goal, it will stand still, jump a bit but not move.

**Comment by Karang** [comment]
You can get the current goal using `bot.pathfinder.goal`

**Comment by SinanAkkoyun** [comment]
Oh thanks. The resetPath in setGoal breaks the spamming of setGoal.
Do you have any advice on how to constantly update the targets? (just like it works on bot.pvp.goal = x?)

**Comment by SinanAkkoyun** [comment]
Because in the past I had issues that the pathfinder didnt calculate through when spamming setgoal

**Comment by rom1504** [comment]
> Do you have any advice on how to constantly update the targets? (just like it works on bot.pvp.goal = x?)

it sounds like you want to define a new goal

**Comment by Karang** [comment]
Yes you should do:
```js
if (bot.pathfinder.goal !== goal) bot.pathfinder.setGoal(goal)
```
You cannot do `bot.pathfinder.goal = ...` its read only.

**Comment by SinanAkkoyun** [comment]
Thanks, well that solves my issue!

But I don't know if all the examples under mineflayer are still working that constantly do setGoal

**Comment by rom1504** [comment]
> constantly do setGoal

as I said, it sounds like you need to define a new goal type *instead* of doing constantly setGoal
here are some examples https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/lib/goals.js

**Comment by SinanAkkoyun** [comment]
Oh, thats what you mean! Yeah, I am already doing that.

**Comment by SinanAkkoyun** [comment]
> > constantly do setGoal
> 
> as I said, it sounds like you need to define a new goal type *instead* of doing constantly setGoal
> here are some examples https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/lib/goals.js

Thank you very much!!!
