### ISSUE TITLE
distanceSquared is not a function crash when the bot has to place/remove blocks

### ISSUE THREAD

**Issue by Slord6** [PrismarineJS/mineflayer-pathfinder#109]
MC version: `1.16.5`
Pathfinder version from package.json: `"mineflayer-pathfinder": "^1.3.6"`

The error I'm seeing is:

```
node_modules\mineflayer-pathfinder\index.js:157
      const dist = botPosition.distanceSquared(node)
                               ^

TypeError: botPosition.distanceSquared is not a function
    at pathFromPlayer (D:\samlo\Documents\Repos\MC-Fren\node_modules\mineflayer-pathfinder\index.js:157:32)
    at EventEmitter.monitorMovement (D:\samlo\Documents\Repos\MC-Fren\node_modules\mineflayer-pathfinder\index.js:264:7)
    at EventEmitter.emit (events.js:315:20)
    at Timeout.doPhysics [as _onTimeout] (D:\samlo\Documents\Repos\MC-Fren\node_modules\mineflayer\lib\plugins\physics.js:63:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

This can be recreated by setting a bot's target to be the top of a nerd-pole so it cannot reach the destination without breaking or placing blocks.

I've been able to fix it locally by refactoring `pathFromPlayer` to use `const botPosition = new Vec3(bot.entity.position.x, bot.entity.position.y, bot.entity.position.z);` and referencing `botPosition` rather than `bot.entity.position`.

Happy to put in a PR if this seems like a sensible solution, but could be I've got something misconfigured.

**Comment by Karang** [comment]
Is it only 1.16.5 or also for 1.16.4 ? I don't think mineflayer was properly updated for 1.16.5, it was added to mcdata only a few days ago.

**Comment by Slord6** [comment]
I've just shutdown my PC, but will check and get back to you tomorrow

**Comment by Slord6** [comment]
Just checked with 1.16.4, still happens

**Comment by Karang** [comment]
It seems that you modified pathfinder, this is what v1.3.6 L157 is supposed to look like https://github.com/PrismarineJS/mineflayer-pathfinder/blob/ba87da967db1feb75b6bd98542b1b0456f72ba29/index.js#L157 Can you try and show the error on an unmodified version ?

**Comment by Slord6** [comment]
Just deleted node_modules and did a fresh `npm i` and I'm still seeing the issue. I've modified one of the examples to minimise the chances that it's something else I've changed which also still causes the issue.

Repro script:
```Javascript
const mineflayer = require('mineflayer')
const { pathfinder, Movements } = require('mineflayer-pathfinder')
const { GoalNear, GoalBlock, GoalXZ, GoalY, GoalInvert, GoalFollow } = require('mineflayer-pathfinder').goals

if (process.argv.length > 6) {
  console.log('Usage : node test.js [<host>] [<port>] [<name>] [<password>]')
  process.exit(1)
}

const bot = mineflayer.createBot({
  host: process.argv[2] || 'localhost',
  port: parseInt(process.argv[3]) || 25565,
  username: process.argv[4] || 'pathfinder'
})

bot.loadPlugin(pathfinder)

bot.once('spawn', () => {
  // Once we've spawn, it is safe to access mcData because we know the version
  const mcData = require('minecraft-data')(bot.version)

  // We create different movement generators for different type of activity
  const defaultMove = new Movements(bot, mcData)

  bot.on('path_update', (r) => {
    const nodesPerTick = (r.visitedNodes * 50 / r.time).toFixed(2)
    console.log(`I can get there in ${r.path.length} moves. Computation took ${r.time.toFixed(2)} ms (${r.visitedNodes} nodes, ${nodesPerTick} nodes/tick)`)
  })

  bot.on('goal_reached', (goal) => {
    console.log('Here I am !')
  })

  bot.on('chat', (username, message) => {
    if (username === bot.username) return

    const target = bot.players[username] ? bot.players[username].entity : null
    if (message === 'come') {
      if (!target) {
        bot.chat('I don\'t see you !')
        return
      }
      const p = target.position

      bot.pathfinder.setMovements(defaultMove)
      bot.pathfinder.setGoal(new GoalNear(p.x, p.y, p.z, 1))
    }
  })
})
```

Called with `node followbot.js <server> <port>`
If I stand on a cobblestone nerd-pole 2 or more blocks high, with the bot a couple of blocks away at ground level then I get the same crash and stack trace

**Comment by Karang** [comment]
Cannot reproduce with your code: its working fine on a clean install. Can you add a `console.log(bot.entity.position)` before the faulty line ?
I'm pretty sure you have an other plugin messing with the player position. The error `distanceSquared is not a function` means that somehow the position is not a vec3.

**Comment by Slord6** [comment]
Huh, bizarre; I setup a new project and also don't see the issue.

Adding a console log (`console.log(bot.entity.position, bot.entity.position.distanceSquared);`) before that line gives `Vec3 { x: 10.5, y: 72, z: 25.62740005009236 } undefined]`

I've done a project-wide search for assignments to bot.entity.position but don't see anything so no idea what's going on.

**Comment by Karang** [comment]
Which version of node-vec3 did you install ? https://github.com/PrismarineJS/node-vec3/blob/master/index.js#L94

**Comment by Slord6** [comment]
Yep - that's the issue. For some reason running an `npm i` with deps:

```
