### ISSUE TITLE
Gets banned on hypixel when trying to build

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#110]
Disclaimer: I suspected this will happen BUT:

The bot just gets banned when trying to stack up. He is not even placing blocks somewhere where his crosshair is not (cause when towering he should place the crosshair where it belongs)

I saw that he could not look down to the block.

Is there a way I could improve things like adding a smoothing or even lerping to the aim, I mean could you please provide me the source files where to look for? 

Thank you so much, when I gave him proper head movement AND legit bridging (will do myself if nobody has a base ofc) I will also do a pull request!

Thanks!!

**Comment by SinanAkkoyun** [comment]
I just saw that this is a mineflayer issue.

Nontheless, how would you go about implementing a proper sneak bridging? In mineflayer as a function? Well, rather in pathfinder, sneak, walk backwards and when on an edge placeBlock, right?

Thank you guys for your great work! :)

**Comment by Karang** [comment]
There is already a PR open about that https://github.com/PrismarineJS/mineflayer-pathfinder/pull/105
I just need to take some time to test it and merge.

**Comment by SinanAkkoyun** [comment]
Small n00b question: How can I use/implement it rn?

**Comment by SinanAkkoyun** [comment]
Ok, I did "npm install PrismarineJS/mineflayer-pathfinder#pull/105/head"
