### ISSUE TITLE
Add a "fall damage" cost or let us decide up to which health we want him to fall

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#111]
Or please tell me where to find the corresponding code where I could implement this!

I am not new to programming at all but I totally am to NodeJS, hence I don't quite understand where some of the code originates... :)

**Comment by Karang** [comment]
There is already the option maxDropDown in movements that you can edit. It defaults to 4 blocks, but you can increase it.
