### ISSUE TITLE
GoalGetToBlock isEnd treats being at destination exactly as being adjacent

### ISSUE THREAD

**Issue by Slord6** [PrismarineJS/mineflayer-pathfinder#114]
The description of GoalGetToBlock says "Don't get into the block, but get directly adjacent to it.". However, if the Mineflayer agent's goal is an air block that it is already stood in, then it treats the goal as reached. This is an issue if the bot needs to place a block at that position as that is not possible when the agent is stood in place.

Relevant code link:
https://github.com/PrismarineJS/mineflayer-pathfinder/blob/ffc8d3c7e03e3ed5f0d320ef5ac25cc666d3c76a/lib/goals.js#L118

Is it possible to aim specifically for adjacent blocks currently? 

Edit: Possibly relates to (closed) PR #23 and Issue #38

**Comment by Karang** [comment]
Yes, good point, should add a check for node != this in the isEnd function

**Comment by Karang** [comment]
Done

**Comment by Slord6** [comment]
Great! Thankyou :)
