### ISSUE TITLE
Deep diving no path found

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#117]
When diving deep the follow goal does not find a path and the bot is "stuck" until one swims up.
I would suggest if the target is in water maybe dynamically switching to a xz goal might do the trick.

I am sorry, I don't really know how to implement this, otherwise I would

**Comment by IceTank** [comment]
This can be done by force canceling the current goal with `setGoal(null)` and then setting a new goal to swim up or just setting the control state to jump. 

We will likely not implement this feature as resetting the goal to a previous goal is not really intended and would break a lot off things.
