### ISSUE TITLE
Is stuck at current position

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#122]
latest everything

Hey, sadly the bot sometimes just gets stuck after spawning.

He bugs at the spot, not able to jump and not able to do anything. Only a kill can cure it...

**Comment by Minecon724** [comment]
i have the same issue
how did you fix it?

**Comment by koneshnoVasya** [comment]
same

**Comment by Minecon724** [comment]
> i have the same issue
> how did you fix it?

anyone?

**Comment by aesthetic0001** [comment]
steps to reproduce?

**Comment by Minecon724** [comment]
still an issue
