### ISSUE TITLE
Code Works just sometimes

### ISSUE THREAD

**Issue by 1jokras** [PrismarineJS/mineflayer-pathfinder#123]
Hello, I have this code:

`const mineflayer = require('mineflayer')
const { pathfinder, Movements, goals } = require("mineflayer-pathfinder")
const pvp = require('mineflayer-pvp').plugin
const GoalNear = goals.GoalNear

const bot = mineflayer.createBot({
    host: 'localhost', // optional
    username: 'JokrasBotTest', // email and password are required only for
})

bot.loadPlugin(pathfinder)

function fellingTrees(){
    const mcData = require('minecraft-data')(bot.version)
    const movements = new Movements(bot, mcData)
    bot.pathfinder.setMovements(movements)
    const LogsArray = [mcData.blocksByName.oak_log.id, mcData.blocksByName.spruce_log.id, mcData.blocksByName.birch_log.id, mcData.blocksByName.jungle_log.id, mcData.blocksByName.acacia_log.id, mcData.blocksByName.dark_oak_log.id]
    const WoodLog = bot.findBlock({matching: LogsArray})
    if (!WoodLog){
        bot.chat("Warum ist hier nirgends Holz")
        return
    }
    const goal = new GoalNear(WoodLog.position.x, WoodLog.position.y, WoodLog.position.z, 3)
    bot.pathfinder.setGoal(goal)
    bot.dig(WoodLog,true, function(){bot.stopDigging();fellingTrees()})

}
bot.on('chat', function (username, message) {
    if (username === bot.username) return
    if (message === "los"){
        fellingTrees()
    }
  })`
and this wokrs sometimes, but some times the bot does not dig but thinks he has diged
(Thanks for Help, and sorry for bad English)

**Comment by Karang** [comment]
This is not an issue with pathfinder.
