### ISSUE TITLE
Pathfinde don't want walk "over" wheat

### ISSUE THREAD

**Issue by sefirosweb** [PrismarineJS/mineflayer-pathfinder#129]
Hello I saw when pathfinder want to cross wheat they think is a solid block (or similar as lava) and try to go with other way

Where is saved this info for made a PR?

**Comment by Karang** [comment]
This is a configurable option from user code, by default pathfinder dont want to walk into crops (to avoid messing farms) https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/lib/movements.js#L45

**Comment by sefirosweb** [comment]
Oooh i see,

Then i need to use in movements:

```js
 movements.blocksToAvoid.delete(XXX)
```

But this not have a sense, only affects to wheat, in this case must be add potatoes, carrots, melons...
Well al plants

Right?

For my case I can remove it, but for generic use maybe need to best way is add a "avoid plants"

**Comment by Karang** [comment]
The id that are given must be the id of blocks, we cant give categories. But you are right this doesnt work for other plants. Maybe we shouldn't put any default and let the user add them for their needs.

**Comment by sefirosweb** [comment]
I'm align, maybe only need to document this behavior if anyone want to use it,

In my case i'm making a farmer bot, and when is a full of wheat they can't walk he gets totally locked up xD

**Comment by magicaltoast** [comment]
I think that would be sane default to allow walking on crops but now 'falling' on them because only this breaks them, and add to constructor something like allow falling on crops

**Comment by sefirosweb** [comment]
Guys I close the issue because this can be changed easly for each one

```js
        movements.blocksToAvoid.delete(mcData.blocksByName.wheat.id)
        movements.blocksToAvoid.add(mcData.blocksByName.sweet_berry_bush.id)
```

Also it is not a "problem" it is rather subjective for the purpose of your bot

**Comment by maximmasiutin** [comment]
@sefirosweb - can you please check that after #303 is is OK by default, without the need to add lines?
