### ISSUE TITLE
Pathfinding up 2 blocks has wrong cost function

### ISSUE THREAD

**Issue by IceTank** [PrismarineJS/mineflayer-pathfinder#131]
When pathfinding up 2 block in a strait line the cost is wrong. The bot should move in a strait line for but path finds in a zigzag pattern:

![pathfing](https://user-images.githubusercontent.com/61137113/110867481-178ab080-82c7-11eb-8d07-90ff07bab6b2.gif)

**Comment by Karang** [comment]
could be solve by adding 1 to the cost here https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/lib/movements.js#L281

**Comment by IceTank** [comment]
Should the cost increase not been somewhere around here as it is in the getMoveDiagonal function? https://github.com/PrismarineJS/mineflayer-pathfinder/blob/88b3785bc7ed3323100c2f725d1c26f81eceb238/lib/movements.js#L281

**Comment by IceTank** [comment]
Is there a cost for jumping? If not I could make a new issue.

**Comment by Karang** [comment]
The cost for jumping is a bit arbitrary, i've set it to +1 when you jump up, but add no penality when you move down or jump over a gap. Cost should really be modified only if you find weird behaviors (like this bug you found) otherwise, what's in atm seems to be working fine.

**Comment by IceTank** [comment]
Reducing jump needed for pathfinding might be usefull in situations were it is important to conserve hunger.
