### ISSUE TITLE
Request for example: GoalCompositeAll

### ISSUE THREAD

**Issue by DatArnoGuy** [PrismarineJS/mineflayer-pathfinder#135]
I tried to use GoalCompositeAll but didn't manage to get my code working. It would be great to get working example how goal array should work.

My non-working code:
      const maalit = new Array();
      maalit.push(new GoalFollow(target2, 3));
      maalit.push(new GoalInvert(new GoalFollow(target, 5)));
      bot.pathfinder.setMovements(defaultMove);
      bot.pathfinder.setGoal(GoalCompositeAll(maalit), true);

**Comment by mat-1** [comment]
You probably need to do `new GoalCompositeAll` instead of just `GoalCompositeAll`

**Comment by Jovan-04** [comment]
what needs to happen here? just writing an example that uses `goalCompositeAll`?

**Comment by IceTank** [comment]
Yes a detailed explanation and examples of how the composite goals work would be great
