### ISSUE TITLE
bot.game.dimension returns the dimension the bot logged on instead of the current one

### ISSUE THREAD

**Issue by japa4551** [PrismarineJS/mineflayer-pathfinder#136]
Hello, today i asked around the Discord if someone knew a fix for this problem but nothing pooped up, so i decided to open this Issue Page. 

Every time i try to print bot.game.dimension, it always print out the dimension the bot logged in, even if i'm in another dimension at the moment. i'm trying to print it with the following command: 

console.log(`The bot has been killed at ${bot_current_position} by ${bot_nearest_player.username} on dimension ${bot.game.dimension}`)

Another user was also having this problem, he mentioned that the problem happend for him before the "Karangs world refactor".

**Comment by u9g** [comment]
this should be in mineflayer

**Comment by japa4551** [comment]
I'll move it to Mineflayer then, thx
