### ISSUE TITLE
Not moving when goal set 

### ISSUE THREAD

**Issue by cojored** [PrismarineJS/mineflayer-pathfinder#138]
I am setting the goal and the bot is not moving....

**Comment by cojored** [comment]
I have tried on a paper and spigot server both version 1.16.5

**Comment by cojored** [comment]
It was one of my plugins

**Comment by chillyspirit** [comment]
What plug-in was it?

**Comment by cojored** [comment]
@chillyspirit It was a plugin that gave the bot a skin I don't remember what the name was
