### ISSUE TITLE
Walking very slow....

### ISSUE THREAD

**Issue by TheDeaX-Lab** [PrismarineJS/mineflayer-pathfinder#15]
Previously, I used mineflayer-navigate and it moved much faster, as I switched to pathfinder, its walking speed was 4 seconds per 1 block, is there any configuration to improve its walking speed? Nor can it resist the movement of water

**Comment by Karang** [comment]
4s / block is not normal, but without more detail we can't help you. For water movement, that's normal to be pushed by water, it should however be able to go against the current (maybe it's related to your first issue). Anyway, walking speed and water movement is controlled by mineflayer's physics, open an issue there https://github.com/PrismarineJS/mineflayer/issues.

**Comment by TheDeaX-Lab** [comment]
@Karang my physics ```{
  gravity: 0.8,
  airdrag: 0.98,
  yawSpeed: 3,
  sprintSpeed: 1.3,
  sneakSpeed: 0.3,
  stepHeight: 0.6,
  negligeableVelocity: 0.003,
  soulsandSpeed: 0.4,
  ladderMaxSpeed: 0.15,
  ladderClimbSpeed: 0.2,
  playerHalfWidth: 0.3,
  playerHeight: 1.8,
  waterInertia: 0.8,
  lavaInertia: 0.5,
  liquidAcceleration: 0.02,
  airborneInertia: 0.91,
  airborneAcceleration: 0.02,
  defaultSlipperiness: 0.6,
  outOfLiquidImpulse: 0.3,
  autojumpCooldown: 10,
  adjustPositionHeight: [Function (anonymous)],
  simulatePlayer: [Function (anonymous)]
}```

**Comment by Karang** [comment]
No you need to give more details, like the code you use, the mineflayer version, etc...
Also, try to run the example.

**Comment by TheDeaX-Lab** [comment]
https://youtu.be/mFVM9QG4yQY

```js
{
                command: "подойди",
                func(username) {
                    const {position: p} = bot.players[username].entity;
                    bot.pathfinder.setMovements(defaultMove)
                    bot.pathfinder.setGoal(new GoalNear(p.x, p.y, p.z, 1))
                }
            }```

**Comment by Karang** [comment]
The full code ? Try to extract a minimal example that reproduce the behavior. Have you tried the example https://github.com/Karang/mineflayer-pathfinder/blob/master/examples/test.js ?

**Comment by TheDeaX-Lab** [comment]
![image](https://user-images.githubusercontent.com/28222565/86541718-c8aaa100-bf17-11ea-9bec-cb5bd492ebb0.png)
pistons can trigger to update path?

**Comment by Karang** [comment]
yes any block update close to the path will trigger a path update. Is that your issue ?

**Comment by TheDeaX-Lab** [comment]
> yes any block update close to the path will trigger a path update. Is that your issue ?

yes, its problem.... I have big melon farm with many pistons, If it updates with every piston, this is of course a failure

**Comment by Karang** [comment]
I committed a fix. Could you try it and tell me if it fix your issue ?
In package.json: `"mineflayer-pathfinder": "Karang/mineflayer-pathfinder"`
Then remove `package-lock.json` and redo `npm install`

**Comment by TheDeaX-Lab** [comment]
> I committed a fix. Could you try it and tell me if it fix your issue ?
> In package.json: `"mineflayer-pathfinder": "Karang/mineflayer-pathfinder"`
> Then remove `package-lock.json` and redo `npm install`

I'll try tomorrow, thanks for the support

**Comment by TheDeaX-Lab** [comment]
> I committed a fix. Could you try it and tell me if it fix your issue ?
> In package.json: `"mineflayer-pathfinder": "Karang/mineflayer-pathfinder"`
> Then remove `package-lock.json` and redo `npm install`

@Karang 
[log.txt](https://github.com/Karang/mineflayer-pathfinder/files/4877359/log.txt)
Also thinks for a long time

**Comment by Karang** [comment]
Are you sure you updated to the latest commit ? (not the release on npm, the master branch on git)
With the fix, unless you are walking on the piston, it shouldn't recompute.

**Comment by TheDeaX-Lab** [comment]
> Are you sure you updated to the latest commit ? (not the release on npm, the master branch on git)
> With the fix, unless you are walking on the piston, it shouldn't recompute.
> 
> Make sure you have these changes [00b4469](https://github.com/Karang/mineflayer-pathfinder/commit/00b4469f0a9a16281cbaaa4cfd6b67af5ff6bdcf)

yes, i have changes. Everything is also repeated as shown in the log
![image](https://user-images.githubusercontent.com/28222565/86568426-844dee00-bf75-11ea-8a2a-7a7f8d0e6d0d.png)

**Comment by Karang** [comment]
ok, try the latest version

**Comment by TheDeaX-Lab** [comment]
@Karang He just turns but doesn't move now. Can you give me a copy of the world for testing?

**Comment by Karang** [comment]
I suppose you meant to ask if you could give me a copy of your world to reproduce the issue ? that would be great

**Comment by TheDeaX-Lab** [comment]
> I suppose you meant to ask if you could give me a copy of your world to reproduce the issue ? that would be great

[melonfarm.zip](https://github.com/Karang/mineflayer-pathfinder/files/4877863/melonfarm.zip)
1.12.2 version world

**Comment by TheDeaX-Lab** [comment]
@Karang you have alternative solution?

**Comment by Karang** [comment]
Not without being able to reproduce. One thing you can try is to monitor the physicTick event to check that its properly called every 50ms.
Add somewhere:
```js
const { performance } = require('perf_hooks')
let start = performance.now()
bot.on('physicTick', () => {
  console.log(performance.now() - start) // should report 50 ms
  start = performance.now()
})
```
You can also add a log in the path_update event to see if the path is still being recomputed too often.
