### ISSUE TITLE
Certain scaffolding blocks not being used by mineflayer

### ISSUE THREAD

**Issue by steadman1** [PrismarineJS/mineflayer-pathfinder#154]
when i add any type of wool or leaves, my mineflayer bot doesn't ever use the blocks.
`
movements.scafoldingBlocks = [
    mcData.blocksByName.white_wool.id,
    mcData.blocksByName.orange_wool.id,
    mcData.blocksByName.dark_oak_leaves.id,
]
`
when i add block ids for stone and dirt they work though.

**Comment by Karang** [comment]
Yes that's a mistake in the examples and code that i need to fix. ScafoldingBlocks expect item id and not block id. So it works for some ids that are the same for the item and block but most don't work.

The correct way to define that is: `movements.scafoldingBlocks = [ mcData.itemsByName.white_wool.id, mcData.itemsByName.orange_wool.id, mcData.itemsByName.dark_oak_leaves.id]`

**Comment by Ender-Haven** [comment]
If all else fails, you can also simply get the block's number IDs from [here](https://www.digminecraft.com/lists/item_id_list_pc_1_8.php), but what Karang said will probably work too.
