### ISSUE TITLE
Bot should backtrack/find other path when stuck

### ISSUE THREAD

**Issue by dylanpdx** [PrismarineJS/mineflayer-pathfinder#177]
I've noticed a behavior that the bot often gets "dead set" on a certain path and won't deviate from it, even if it's impossible
I set up an example where this happens:
`bot.pathfinder.setGoal(new GoalGetToBlock(-4674, 255, 1470))`
Placing the bot at Y 255, far away from the goal and above a body of water makes it head directly for the goal, but reach a dead end, even though it has the option of going back, jumping in the water, and then traversing the world below.
![issue](https://user-images.githubusercontent.com/1337360/123333450-ac917c80-d539-11eb-8c1e-3670b81e6b0a.gif)

**Comment by Karang** [comment]
When the goal is unreachable the bot default to the closest position it can get to. The goal you set is at Y=255, if it doesn't have blocks to go up why would it drop to sea level ? If the goal is to get to a position out of the distance, try to use a XZ goal first to get closer then use an exact GoalGetToBlock when the position is in view.

**Comment by dylanpdx** [comment]
Ah ok, I was thinking it'd behave similar to Baritone, where if the best position doesn't get to the goal, it tries alternative routes, even if it has to change Y levels in the process.
Setting an XZ goal and then a full Block goal seemed to do the trick, thank you!
