### ISSUE TITLE
Typescript does not account for event bot.on('goal_reached')

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#178]
The mineflayer bot events addition after doing loadPlugin do not play nicely with typescript types

```ts
await new Promise((resolve, reject) => {
                    this.bot.pathfinder.setGoal(new mineflayerPathfinder.goals.GoalXZ(pos.x, pos.z))
                    
                    this.bot.on('goal_reached', (goal: any) => {
                        resolve(goal)
                    })
                })
```
It tells me `Argument of type '"goal_reached"' is not assignable to parameter of type 'keyof BotEvents'.ts(2345)`

What can I do?

**Comment by u9g** [comment]
as an alternative: 
```js
import { once } from 'events'
this.bot.pathfinder.setGoal(new mineflayerPathfinder.goals.GoalXZ(pos.x, pos.z))
await once(bot, 'goal_reached')
```

**Comment by SinanAkkoyun** [comment]
Uhh, thank you very much, that's even better!

**Comment by SinanAkkoyun** [comment]
What I actually was looking for:
`await this.bot.pathfinder.goto(new mineflayerPathfinder.goals.GoalXZ(pos.x, pos.z))`
