### ISSUE TITLE
Bot going back and forth, "visibility" issue?

### ISSUE THREAD

**Issue by Garfield100** [PrismarineJS/mineflayer-pathfinder#179]
In testing I've found this strange behaviour by the bot. Simply look at the gif.
There is only one way for the bot to get to me, and that is by taking the narrow way because the way on the main platform is blocked by a wall.
The bot is the player walking back and forth near the gold blocks. It is trying to find a way to me, the player on the right.
Does this have something to do with the bot's "view distance"? If so, how can this be turned up? And why can it see the bridge on the left from so far away, but "loses sight" of the bridge on the right almost immediately?
This does not happen in the opposite direction, i.e. with the player positions swapped.

![ezgif-2-c63e58bc8876](https://user-images.githubusercontent.com/5878721/125102974-660c5800-e0cb-11eb-85f9-1f338dae477b.gif)

**Comment by Karang** [comment]
Increasing the tick timeout should fix the issue https://github.com/PrismarineJS/mineflayer-pathfinder#botpathfinderticktimeout
