### ISSUE TITLE
Wrong work GoalCompositeAll

### ISSUE THREAD

**Issue by olzx** [PrismarineJS/mineflayer-pathfinder#190]
Hi, I ran into a problem when I decided to go several points through GoalCompositeAll.
After starting, the bot comes to the center point and stops.
Help please, is this a bug or am I doing something wrong?

- version: 1.15.2
code:
```js
const blocksCords = [new GoalBlock(81, 64, 46), new GoalBlock(86, 64, 56), new GoalBlock(83, 64, 66)]
const goalAll = new GoalCompositeAll()
blocksCords.forEach(pos => goalAll.push(pos))
bot.pathfinder.setGoal(goalAll)
```
I indicate the movements when the bot spawns, like this:
```js
mcData = bot.sundry.mcData = require('minecraft-data')(bot.version)
const defaultMove = new Movements(bot, mcData)
defaultMove.blocksToAvoid.delete(mcData.blocksByName.wheat.id)
bot.pathfinder.setMovements(defaultMove)
```

**Comment by IceTank** [comment]
GoalCompositeAll is working as intended. It takes in multiple goals and creates a goal that wants to satisfy all goals.
What you want is something like a for loop. 
```js
for (goal of blocksCords ) {
  await bot.pathfinder.goto(goal)
}
```
