### ISSUE TITLE
Disabling a function

### ISSUE THREAD

**Issue by TheOfficialSeb** [PrismarineJS/mineflayer-pathfinder#209]
I want the bot to not be able to dig or mine any blocks.

**Comment by autowert66** [comment]
https://github.com/PrismarineJS/mineflayer-pathfinder#candig

**Comment by IceTank** [comment]
Look at the movements.js example. It tells you how you can prevent to bot from digging or mining blocks https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/examples/movements.js
