### ISSUE TITLE
Took to long to decide path to goal!

### ISSUE THREAD

**Issue by foxodever** [PrismarineJS/mineflayer-pathfinder#213]
![image](https://user-images.githubusercontent.com/52624723/137640302-5ee073f8-e411-46c5-bc97-fda8fe96f28b.png)
It happens every 2 minutes after start

**Comment by oscarspalk** [comment]
do you still have this issue, or is it solved?

**Comment by IceTank** [comment]
Closing because too old

**Comment by GoingMyWay** [comment]
Same issue. If the goal is not reachable. `goto` should stop and warn user.

**Comment by IceTank** [comment]
> Same issue. If the goal is not reachable. goto should stop and warn user.

I don't know what you mean. goto stops with either a timeout or a noPath result when there is no path. If you have an issue with it you should make an issue.

Regarding this issue. Goto did return. It just rejected the promise. Pathfinder can not catch the rejected promise for you. If you don't want any errors or return value you can use setGoal.

**Comment by GoingMyWay** [comment]
> > Same issue. If the goal is not reachable. goto should stop and warn user.
> 
> I don't know what you mean. goto stops with either a timeout or a noPath result when there is no path. If you have an issue with it you should make an issue.
> 
> Regarding this issue. Goto did return. It just rejected the promise. Pathfinder can not catch the rejected promise for you. If you don't want any errors or return value you can use setGoal.

Thanks for the clarification. I misunderstood the issue. I understand the point. I managed to throw this exception in my project. It works.

BTW, are there any methods that can add a customised function in `goto` so that the bot can stop moving when some conditions are met in the customised function. For example, the bot will stop before step into the water, though that is the target destination.

**Comment by IceTank** [comment]
No. If you want to cancel the goto, you can call bot.pathfinder.stop() or set the current goal to null.
If you want to stop before touching water, I would suggest you make a custom goal that walks up to water but does not go into it.

**Comment by GoingMyWay** [comment]
> No. If you want to cancel the goto, you can call bot.pathfinder.stop() or set the current goal to null. If you want to stop before touching water, I would suggest you make a custom goal that walks up to water but does not go into it.

Thank you. I will try the customised goal.
