### ISSUE TITLE
Bot gets stuck on blocks

### ISSUE THREAD

**Issue by MyUsernamee** [PrismarineJS/mineflayer-pathfinder#223]
Sometimes the bot will try to move in a way the server doesn't like. This will cause the server to tell the bot to move back to a valid spot. The issue is that the bot will continue to try and make that move even though it may not be valid.

Steps to reproduce:
1. Create a bot.
2. Join some dedicated server.
3. Give the bot a pickaxe.
4. Mine to bedrock.
5. Try to resurface.
Sometimes the bot will clip a block and get stuck. Looking through the prismarine viewer you can see it is be sent back by the server.

**Comment by IceTank** [comment]
You have to give more info on this. If there is an issue with hit boxes you should make an issue in prismarine-physics. If there is an issue with invalid moves that is a different thing. In that case you should give an example with a specific move that does not work. Pathfinder is usually tested on vanilla servers. Is the server you are using a different brand off server compared to vanilla? Does it have any movement related plugins like anti cheat? What version where you using when the issue occurred?

**Comment by MyUsernamee** [comment]
Ok, I was on a vanilla minecraft 1.16.5 server.
It looks like it could be a issue with the hit boxes but I am unsure.
It looks like it is a issue with invalid moves, specifically on diagonals with a block in the way of the path. It also seems to happen when the bot clips its head on a downward diagonal.
All movement settings are default.


Here is a example of a illegal move as seen from primarine-viewer and minecraft
![ezgif-2-c4f80d02eda5](https://user-images.githubusercontent.com/86261814/146126327-8537b1b6-683e-486a-92e4-5f6c964dd8c0.gif)

**Comment by MyUsernamee** [comment]
Ok so I think I fixed it, if you add 0.05 to the bot's width and height, it fixes this issue. So it seems like this is a physics issue. Thank you for the help!

**Comment by IceTank** [comment]
> Ok so I think I fixed it, if you add 0.05 to the bot's width and height, it fixes this issue. So it seems like this is a physics issue. Thank you for the help!

I think hitboxes changed in 1.8 1.9 somewhere. prismarine-physics might not handle that case correctly if the hitbox is wrong.

**Comment by Eld3rly** [comment]
Hey, I'm starting to make my own bots and I have the same problem.
Can you please tell me how you added 0.05 to the height and width of the bot?
Thanks!
