### ISSUE TITLE
Error on movement.js 

### ISSUE THREAD

**Issue by DonTMover** [PrismarineJS/mineflayer-pathfinder#258]
![image](https://user-images.githubusercontent.com/46960051/163601723-c980a4e3-532a-456f-854a-49dfbaeaa128.png)
 I can't run

**Comment by IceTank** [comment]
You are not using the movements class correctly or your mcData is outdated.

**Comment by DonTMover** [comment]
![image](https://user-images.githubusercontent.com/46960051/163602721-2bde16e6-f4ea-422b-ae23-778e4191f749.png)
this is a code

**Comment by DonTMover** [comment]
![image](https://user-images.githubusercontent.com/46960051/163602768-974a9432-7c2f-4a04-8a4a-e8eb1d67a0ad.png)

**Comment by DonTMover** [comment]
maybe you see error in my code?

**Comment by IceTank** [comment]
`bot.regestry` is not a thing so mcData will be undefined. You need to wait for the bot to spawn before importing mcData. Look at the pathfinder examples.

**Comment by DonTMover** [comment]
I'll take a look now.

**Comment by DonTMover** [comment]
![WindowsTerminal_4LewUz6Mpu](https://user-images.githubusercontent.com/46960051/163621732-0979209f-c2f5-42e0-a031-952069200040.png)
No, it didn't. 
![image](https://user-images.githubusercontent.com/46960051/163621773-f27fe194-4c31-49cd-bb3a-5f69cb830bd0.png)

**Comment by IceTank** [comment]
You are still doing it wrong you need to wait for the bot to spawn before importing minecraft-data. bot.version will be undefined before the bot spawned. Look at the pathfinder examples and use those.

**Comment by DonTMover** [comment]
![image](https://user-images.githubusercontent.com/46960051/163672328-c83589d1-a17e-4ccd-b6b1-7ee3e8facc63.png)
![image](https://user-images.githubusercontent.com/46960051/163672336-e592885b-4cdd-4bb3-8c4c-8a6958b943e9.png)
When I try to use examples, it still does not start

**Comment by IceTank** [comment]
What version is the server you are trying to join? If it is a server between version 1.8 and 1.18 then try running `npm update` to update minecraft-data.

**Comment by DonTMover** [comment]
1.18.2 , 
![image](https://user-images.githubusercontent.com/46960051/163679368-32d757e8-4069-493a-aed7-6613b4806eab.png)
i updated , but not work

**Comment by DonTMover** [comment]
oops, also tested on 1.16.5

**Comment by IceTank** [comment]
This is an issue with your setup. The errors about 'Cannot read property of of null' is because you are using an old version of mcData. The last screenshot has an error because app.start() is not defined.
