### ISSUE TITLE
GoalBreakBlock Cannot read properties of undefined (reading 'distanceTo')

### ISSUE THREAD

**Issue by Sunderw3k** [PrismarineJS/mineflayer-pathfinder#260]
This is my code:
```js
const mineBlock = (bot, block_name) => {
    const mcdata = require("minecraft-data")(bot.version);

    const coords = bot.findBlockSync({
        point: bot.entity.position,
        matching: mcdata.blocksByName[block_name].id,
        maxDistance: 256
    })[0].position;

    if (!coords) { return };

    const defaultMove = new Movements(bot, mcdata);
    bot.pathfinder.setMovements(defaultMove);

    const goal = new GoalBreakBlock(coords.x, coords.y, coords.z, bot)
    console.log(coords)
    bot.pathfinder.goto(goal).then(() => {
        const block = bot.blockAt(coords);
        bot.tool.equipForBlock(block);
        bot.dig(block)
    })
}
```
everything works fine until i try to goto the goal. Whats the issue?

**Comment by IceTank** [comment]
Post the full error

**Comment by Sunderw3k** [comment]
```
C:\Users\Sun3k\Desktop\Coding\BotFlood\node_modules\mineflayer-pathfinder\lib\goals.js:175
    if (node.distanceTo(this.pos.offset(0, this.entityHeight, 0)) > this.reach) return false
             ^

TypeError: Cannot read properties of undefined (reading 'distanceTo')
    at GoalLookAtBlock.isEnd (C:\Users\Sun3k\Desktop\Coding\BotFlood\node_modules\mineflayer-pathfinder\lib\goals.js:175:14)
    at GoalBreakBlock.isEnd (C:\Users\Sun3k\Desktop\Coding\BotFlood\node_modules\mineflayer-pathfinder\lib\goals.js:216:22)
    at EventEmitter.monitorMovement (C:\Users\Sun3k\Desktop\Coding\BotFlood\node_modules\mineflayer-pathfinder\index.js:367:23)
    at EventEmitter.emit (node:events:539:35)
    at Timeout.doPhysics [as _onTimeout] (C:\Users\Sun3k\Desktop\Coding\BotFlood\node_modules\mineflayer\lib\plugins\physics.js:66:13)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

Node.js v17.8.0
```

**Comment by IceTank** [comment]
Try updating pathfinder with `npm update`. You seam to be using an older version.

**Comment by Sunderw3k** [comment]
I installed it yesterday, pretty sure everything is up to date
```js
mineflayer-pathfinder@2.0.0 | MIT | deps: 7 | versions: 39

dependencies:
minecraft-data: ^2.75.0    prismarine-entity: ^2.0.0  prismarine-nbt: ^2.0.0     vec3: ^0.1.7
prismarine-block: ^1.7.3   prismarine-item: ^1.5.0    prismarine-physics: ^1.2.2```

**Comment by Sunderw3k** [comment]
I've read the docs and found out that GoalBreakBlock is deprecated. ```
js
const mineBlock = async (bot, block_name) => {
    bot.stopDigging();
    bot.pathfinder.stop();
    const mcdata = require("minecraft-data")(bot.version);
    const id = mcdata.blocksByName[block_name]?.id

    if (!id) { return }

    await bot.findBlock({
        point: bot.entity.position,
        matching: id,
        maxDistance: 256
    }, (error, blocks) => {
        if (blocks.length) {
            const defaultMove = new Movements(bot, mcdata);
            bot.pathfinder.setMovements(defaultMove);

            const goal = new GoalLookAtBlock(blocks[0].position, bot.world);
            bot.pathfinder.goto(goal).then(() => {
                const block = bot.blockAt(blocks[0].position);
                bot.tool.equipForBlock(block);
                bot.dig(block, "ignore").then(() => {
                    mineBlock(bot, block_name)
                })
            });
        }
    });
}
```

For anyone wondering this is what I did.

**Comment by IceTank** [comment]
This is just a guess as that error is really weird but I think one off those is either NaN or null/undefined `coords.x, coords.y, coords.z`

**Comment by IceTank** [comment]
Or you are calling that function before the bot's position is in a defined state

**Comment by IceTank** [comment]
> For anyone wondering this is what I did

No. This code has multiple errors and will never work. findBlock is not asynchronous and dose not need either a callback or an await. It only takes one argument so the callback will never be called. findBlock will return an instance off a block or null not an array off blocks so blocks.length will always be undefined. Only findBlocks returns an array off results but not off block instances but Vec3 instances so blocks[0].position will also be undefined. bot.pathfinder.stop() is also not synchronous and will not work correctly when you do not await it you might as well use bot.pathfinder.setGoal(null).
