### ISSUE TITLE
Bot completely stopping on bot.pathfinder.stop(); or bot.pathfinder.setGoal(null);

### ISSUE THREAD

**Issue by Sunderw3k** [PrismarineJS/mineflayer-pathfinder#261]
This is probably something simple I dont know about, but the bot completely dies with either 
```js
PathStopped: Path was stopped before it could be completed! Thus, the desired goal was not reached.
```
or
```js
GoalChanged: The goal was changed before it could be completed!
```

My code:
```js

bot.on("chat", () => {
    if (message == "stop") {
        bot.pathfinder.stop();
        bot.stopDigging();
    }
});
```

**Comment by IceTank** [comment]
`bot.pathfinder.goto` will throw an error when the bot has to stop pathing before it has reached it's goal. This can happen when you call `bot.pathfinder.stop()` or set a new goal before pathfinder completed it's goal. You can fix this by handling catching the promise rejection off goto.

**Comment by IceTank** [comment]
Also it is easier if you go ask these types off questions in the discord instead.

**Comment by Sunderw3k** [comment]
Oh right, true. Didn't realise theres a discord. I'm pretty new to javascript so would it just be something like this?
```js
bot.pathfinder.goto(goal).then(() => {
                const block = bot.blockAt(blocks[0].position);
                bot.tool.equipForBlock(block);
                bot.dig(block, "true").then(() => {
                    mineBlock(bot, block_name)
                }).catch(() => { })
            });```

**Comment by IceTank** [comment]
you need a .catch somewhere to catch the promise rejection from goto. Or you can use the await keyword and just use a try catch block. You can also chain .catch and .then. See here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

**Comment by Sunderw3k** [comment]
Ive added the catch at the end, and left it empty as I dont want to do anything if the exception occurs. Can you show me an example of how this would look like using try and await?

**Comment by Sunderw3k** [comment]
Also I'm pretty sure it works the way I made it with the catch. From what I understand it tries to go to the spot, if the bot succesfully comes to the spot, then the promise is fulfilled and the .then() is started, but if anything goes wrong then the .catch() handles it. Just for the sake of learning I'd still appreciate the await + try example and we can close the issue.

**Comment by IceTank** [comment]
```js
async function mineBlock(bot, block_name) {
  ...
  try {
    await bot.pathfinder.goto(goal)
    const block = bot.blockAt(blocks[0].position)
    await  bot.tool.equipForBlock(block)
    await bot.dig(block, "true")
  } catch (err) {
    console.error(err)
  }
  mineBlock(bot, block_name).catch(() => { })
}
```

**Comment by Sunderw3k** [comment]
ah okay, makes sense. Thanks for the help!
