### ISSUE TITLE
minDistance???

### ISSUE THREAD

**Issue by 321Proteus** [PrismarineJS/mineflayer-pathfinder#270]
### Hi guys,
if there is a `maxDistance` parameter, is it possible to add the `minDistance` parameter? 

It would mean the distance from which the search would have to be started, previously met entities would not be taken into account. Please think about it, i need it very much for my project

**Comment by IceTank** [comment]
You can make a custom goal that only completes when you are further away. 

Also what do you mean with previously met entities? This sounds more like something you should check in your code and not something pathfinder should handle.
