### ISSUE TITLE
Stuck on farmland

### ISSUE THREAD

**Issue by ripSquid** [PrismarineJS/mineflayer-pathfinder#278]
I am trying to pathfind while starting on a farmland. It just waits for a bit and the event "path_reset" gets activated with the reason "stuck".

**Comment by IceTank** [comment]
Seams to work for me. What version are you using?

**Comment by IceTank** [comment]
Wheat is on the default list off blocks to avoid. When the bot starts within a wheat block he might not be able to go anywhere.

**Comment by ripSquid** [comment]
It might only be in the version on npm. The fix is what I said

**Comment by ripSquid** [comment]
I have planted potatoes so it isn't even wheat. The issue if what I said that it is getting the difference of two floored values. (block position) meanwhile it is supposed to get the difference between the bot position and the block position. So only one of the values is supposed to be floored.

**Comment by ripSquid** [comment]
On line 80
`const p = startPos.floored()`
`const dy = p.y - Math.floor(p.y)`
Here p.y is already floored. So it is comparing `Math.floor(startPos.y) - Math.floor(startPos.y)` while thinking it is `startPos.y - Math.floor(startPos.y)`

**Comment by IceTank** [comment]
I tested 1.12.2 and 1.18.2 and both work fine. I cannot fix what is not broken.

**Comment by ripSquid** [comment]
well you can at least see that dy will always be zero. And it uses that for pathing later on. In no way is that correct.

**Comment by IceTank** [comment]
You are probably doing something wrong. Post the code you are using and what version off minecraft you are playing on. Again farmland works fine for the versions I am using.

**Comment by IceTank** [comment]
> 1.18.2. I fixed the problem by changing those lines I am talking about. Could you show me your setup that is working instead because my code is extremely large and has other stuff embedded everywhere?

I use the example.js in the examples folder

**Comment by IceTank** [comment]
I used come with the example. But standing on the farmland and on top off the farmland both work. There was an issue where the bot would not arrive at a destination block when that block was not full height. But this has been fixed a few weeks ago.

**Comment by ripSquid** [comment]
I have no idea in that case. It got stuck while starting on farmland consistently. I changed around in the code until I searched for issues here where this has happened before. The fix then was a similar code to the code I linked except there it wasn't using floor on both values. I can reply tomorrow if I can reproduce it on a small code snippet.

**Comment by ripSquid** [comment]
I have figured out the problem. While looking back at the old issue made for this. The bot only gets stuck on farmland if there is water or air under the farmland.

**Comment by IceTank** [comment]
Yes with air below the farmland this does indeed not work. This pr should fix it #280

**Comment by IceTank** [comment]
Do you still have issues with this? This should be fixed now. Please re-open the issue if you still have issues.
