### ISSUE TITLE
(MC 1.12.2) fails to break blocks to get to goal

### ISSUE THREAD

**Issue by dement6d** [PrismarineJS/mineflayer-pathfinder#279]
### Info
This issue happens on Minecraft 1.12.2 but not on 1.18.2, i haven't tested other versions

Pathfinder gets stuck on a path_update loop and fails to break blocks to get to the destination.

Environment: 1.12.2 Paper server with ViaVersion 4.3.1 installed.

### Example scenario
Bot is trying to go to the dirt item entity but appears to just be swinging its arm instead of destroying the blocks in the way
![image](https://user-images.githubusercontent.com/93228501/179375244-145f0ca7-abce-4135-978d-6805ab36bc60.png)

package.json:
```json
{
  "type": "module",
  "dependencies": {
    "mineflayer": "^4.3.0",
    "mineflayer-pathfinder": "^2.2.0"
  }
}
```

Here's the code for replicating the issue:
```js
import mineflayerPathfinder from "mineflayer-pathfinder";
const { pathfinder, goals: { GoalNearXZ } } = mineflayerPathfinder;
import mineflayer from 'mineflayer';

const bot = mineflayer.createBot({
    username: "Bot",
    host: "localhost",
    port: 25565,
    version: "1.12.2",
    checkTimeoutInterval: 60 * 1000
})

bot.loadPlugin(pathfinder)

bot.once('spawn', () => {
    bot.on('goal_updated', (goal) => {
        console.log(goal)
    })
    bot.on('path_update', () => {
        console.log("Path updated")
    })
    bot.on('entityMoved', (entity) => {
        const item = entity.getDroppedItem();
        if (!bot.pathfinder.goal && item && item.name === 'dirt') {
            console.log('Set goal for dirt')
            const pos = {
                x: entity.position.x,
                z: entity.position.z
            }
            bot.pathfinder.setGoal(null)
            bot.pathfinder.setGoal(new GoalNearXZ(pos.x, pos.z, 1))
        }
    })
})
```

**Comment by IceTank** [comment]
For fine for me. Did you disable spawn protection?

**Comment by dement6d** [comment]
> For fine for me. Did you disable spawn protection?

i completely forgot spawn protection was a thing man lol. yeah that was it, thanks
