### ISSUE TITLE
Bot cant jump into that structure for no reason. It stucks in the corner

### ISSUE THREAD

**Issue by Grammf** [PrismarineJS/mineflayer-pathfinder#283]
![2022-07-30_19 00 29](https://user-images.githubusercontent.com/89208604/181925231-193b4379-3c5c-478a-aa0f-572dcdf2baa1.png)
![2022-07-30_19 03 11](https://user-images.githubusercontent.com/89208604/181925337-09dc19a6-1655-45cf-87f8-6f42c9d0f35b.png)

**Comment by IceTank** [comment]
Will look at this when I have time

**Comment by IceTank** [comment]
Cannot reproduce. Did you use GoalNear instead off goal block?

**Comment by IceTank** [comment]
Closing this now
