### ISSUE TITLE
Possible bug: Error while creating a movement

### ISSUE THREAD

**Issue by Itsredpro** [PrismarineJS/mineflayer-pathfinder#295]
![image](https://user-images.githubusercontent.com/87329611/199073697-efddab64-b6b8-499e-b197-8cafc7515f4c.png)

```js
const { pathfinder, Movements, goals } = require('mineflayer-pathfinder')


function getMove(numb,bot){
    switch(numb){
        case 0:
            var move = new Movements(bot)
            move.canDig = false
            
            return move
    }
}

getMove(0,bot)
```

Code errors while trying to create a movement, i updated the package to the latest version but that didn't resolve the problem.
Please help me resolve this issue.

**Comment by DEVTomatoCake** [comment]
This package is using an older version of `minecraft-data` which might not have all block data for newer versions. You can try using `npm ls minecraft-data` and find + update any occurence which isnt using the latest version (`3.17.0` currently).

**Comment by Itsredpro** [comment]
I created a new repository and copy pasted everything and that seemed to fix it. Weird.
