### ISSUE TITLE
Bot never goes under layer 0

### ISSUE THREAD

**Issue by mevenG** [PrismarineJS/mineflayer-pathfinder#304]
with `bot.pathfinder.setGoal(new GoalNear(1, -10, 0, 1))` the bot never goes under the layer 0.
It just stops from going where I want, and stops few layers above 0

**Comment by IceTank** [comment]
I don't see why it would not be able to go below 0. I don't have to time to test right now. But I will look into it.

**Comment by IceTank** [comment]
This should be fixed now with version 2.4.2
