### ISSUE TITLE
Not working with Mineflayer 4.5.1?

### ISSUE THREAD

**Issue by Matt-MX** [PrismarineJS/mineflayer-pathfinder#305]
Using the latest version of Mineflayer and Pathfinder.

```
TypeError: Cannot read properties of undefined (reading 'blocksByName')
    at new Movements (F:\PC\Projects\BotSorter\node_modules\mineflayer-pathfinder\lib\movements.js:43:39)
    at StorageBot.start (F:\PC\Projects\BotSorter\src\bot\storageBot.js:26:24)
    at F:\PC\Projects\BotSorter\index.js:24:9
    at Array.forEach (<anonymous>)
    at F:\PC\Projects\BotSorter\index.js:17:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (F:\PC\Projects\BotSorter\index.js:9:8)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
```

I've seen no other complaints about this so I feel it's only me experiencing the issue.
Any ideas of why this is happening?

**Comment by Dufftwt** [comment]
The same is happening to me. With the basic example from mineflayer AND from the readme example.

**Comment by Dufftwt** [comment]
> Using the latest version of Mineflayer and Pathfinder.
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'blocksByName')
>     at new Movements (F:\PC\Projects\BotSorter\node_modules\mineflayer-pathfinder\lib\movements.js:43:39)
>     at StorageBot.start (F:\PC\Projects\BotSorter\src\bot\storageBot.js:26:24)
>     at F:\PC\Projects\BotSorter\index.js:24:9
>     at Array.forEach (<anonymous>)
>     at F:\PC\Projects\BotSorter\index.js:17:14
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (F:\PC\Projects\BotSorter\index.js:9:8)
>     at Module._compile (node:internal/modules/cjs/loader:1099:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:975:32)
> ```
> 
> I've seen no other complaints about this so I feel it's only me experiencing the issue. Any ideas of why this is happening?

Okay, I've just figured it out, the bot needs to be completely spawned before defining using new Movements(bot)
so wait for the bot.on("spawn",...)
the reason why it didn't work like before is because now they use bot.registry, and it seems the bot needs to be fully spawned to be able to access it

**Comment by IceTank** [comment]
I cannot reproduce this issue. Make sure you are using the latest version off mineflayer by running `npm update`

**Comment by IceTank** [comment]
> Okay, I've just figured it out, the bot needs to be completely spawned before defining using new Movements(bot)
so wait for the bot.on("spawn",...)
This should not be an issue tho. Mineflayer should load the registry before loading any external plugins like mineflayer-pathfinder. I think the issue is that you are using a outdated mineflayer version that does not define bot.registry

**Comment by Matt-MX** [comment]
> I cannot reproduce this issue. Make sure you are using the latest version off mineflayer by running `npm update`

I'm running 4.5.1 which is the latest version.

**Comment by IceTank** [comment]
Ok I will make a workaround for when bot.registry is not defined

**Comment by IceTank** [comment]
@Matt-MX Looking at mineflayer again this looks like an issue in in your code and at what time you use new Movements. bot.registry is only defined after the inject_allowed event has been fired by mineflayer. From your stack trace I can see that the reference error is not caused by mineflayer-pathfinder but by your code that is calling new Movements. Make sure you are calling new Movements after the inject_allowed event has fired. Or wait for the bot to spawn. Movements can define its own registry if bot.registry does not exist. But this might cause cause other issues in the future.

**Comment by Matt-MX** [comment]
I got it working now, I simply just applied the movement on the spawn event, like https://github.com/PrismarineJS/mineflayer-pathfinder/issues/305#issuecomment-1354057386
