### ISSUE TITLE
Saying the the mcdata script in the Movements script is undefinded in the code this.blocksCantBreak.add(mcData.blocksByName.chest.id)

### ISSUE THREAD

**Issue by BigFatMan312312** [PrismarineJS/mineflayer-pathfinder#306]

**Comment by BigFatMan312312** [comment]
this is the code i used

const mineflayer = require("mineflayer")
const pathfinder = require('mineflayer-pathfinder').pathfinder
const Movements = require('mineflayer-pathfinder').Movements
const { GoalNear } = require('mineflayer-pathfinder').goals
const bot = mineflayer.createBot({
  username: "TreeBot",
  host: "localhost",
})
bot.mcData = require('minecraft-data')(bot.version)

bot.loadPlugin(pathfinder)

bot.once('spawn', function() {
  bot.mcData = require('minecraft-data')(bot.version)
})


bot.on('chat', function (username, message) {
  if(username === bot.username) return;
  let Wood;
  if(message == "dig"){
    bot.lookAt(bot.entity.position.offset(0, -1, -1))
    let blocks = bot.findBlock({
      matching: bot.mcData.blocksByName["stone"].id,
      maxDistance: 150,
    })
    if(bot.canSeeBlock(blocks) ==  true){
      if(bot.canDigBlock(blocks) == false){
        const defaultMove = new Movements(bot)
        defaultMove.canDig = false
        bot.pathfinder.setMovements(defaultMove)
        bot.pathfinder.setGoal(new GoalNear(blocks.position.x, blocks.position.y, blocks.position.z))
      }
    }else{
      const defaultMove = new Movements(bot)
      defaultMove.canDig = false
      bot.pathfinder.setMovements(defaultMove)
      bot.pathfinder.setGoal(new GoalNear(blocks.position.x, blocks.position.y, blocks.position.z))
    }
    bot.dig(blocks)
    }
  })

**Comment by IceTank** [comment]
You don't have to define bot.mcData on the bot. If you need mcData you should use `bot.registry` that is defined by mineflayer. The rest off the code looks good. The error is due to you not using the latest version of mineflayer-pathfinder. Make sure you are using version 2.4.0 or higher. You can update with `npm update`, or manually changing the version in package.json and then running npm install again.

**Comment by IceTank** [comment]
The version you are using still needs mcData as the second argument in the Movements constructor. Without it you will get a reference error
