### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Dinhero21** [PrismarineJS/mineflayer-pathfinder#307]
There is a possible typo [here](https://github.com/PrismarineJS/mineflayer-pathfinder/blob/8f5e1a59332266db7fed8aa81410b80996fd0c96/readme.md?plain=1#L114).

**Comment by IceTank** [comment]
I am not sure what you mean. You can always open a pull request to fix what you think is wrong.

**Comment by Jovan-04** [comment]
I think OP means that the wording of the description is unclear. 

currently, it's this:

Stops path finding when its save to stop or after the bot encountered an error while path finding. To force stop use bot.pathfinder.setGoal(null). Emits `path_stop` when stopped.


that's difficult to read, and it's not clear what 'safe to stop' means.

perhaps something like this would be better:

Stops pathfinding as soon as the bot has reached a safe location (i.e. standing on solid ground?). Emits `path_stop` when called. 
Note: to force stop immediately, use `bot.pathfinder.setGoal(null)`


also, what does "or after the bot encountered an error while path finding" mean? the `path_stop` event may be emitted then, but don't all errors stop the bot anyway?

**Comment by IceTank** [comment]
Yeah when there is an error it will always stop. It will probably emit the event that corresponds with the error the bot encountered and not the path_stop event. The stop function is designed to stop the bot when it reached the next path node in the current path. So basically it will avoid stopping mid air. This is especially useful as currently when the bot stops path finding it cancels all velocity and could drop like a rock mid jump when not using pathfinder.stop().

**Comment by Jovan-04** [comment]
okay. In that case, I don't think it's necessary to include the error part; I don't see how it's relevant to `bot.pathfinder.stop()`. perhaps we can just rephrase that section of the docs to something like:

Stops pathfinding as soon as the bot has reached the next node in the path (this prevents the bot from stopping mid-air). Emits `path_stop` when called.
Note: to force stop immediately, use `bot.pathfinder.setGoal(null)`

**Comment by Dinhero21** [comment]
What I meant is that it is written as "... its **save** to stop ..." instead of "... its **safe* to stop ..." but I guess that also works.

**Comment by IceTank** [comment]
@Jovan-04 do you have time to make a pr? If not I can make one at some point.

**Comment by IceTank** [comment]
Or someone else is also free to make a pr to fix it

**Comment by Jovan-04** [comment]
> What I meant is that it is written as "... its **save** to stop ..." instead of "... its **safe** to stop ..." but I guess that also works.
yeah, I figured. but if I'm fixing a typo, I may as well make the docs more clear too 
**it looks like the typo you mentioned was on a different branch, that doesn't look like it's being used or updated. @IceTank do you know what's happening with that branch?

> @Jovan-04 do you have time to make a pr? If not I can make one at some point.

redid the wording for master branch in #327
