### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by elamperti** [PrismarineJS/mineflayer-pathfinder#32]
Having documentation would be very helpful (even more than examples!)

Great work with this lib :grin:

**Comment by Karang** [comment]
The API is still evolving, but documentation is indeed needed.

**Comment by rom1504** [comment]
This is starting to be used by many people, would be good to add some doc (for the exposed methods and events) to avoid having to dig through code

**Comment by Karang** [comment]
I think this was mostly done in https://github.com/PrismarineJS/mineflayer-pathfinder/pull/55
