### ISSUE TITLE
The code that is completely identical to the example that used to work normally does not work.

### ISSUE THREAD

**Issue by Vyacheslav73195** [PrismarineJS/mineflayer-pathfinder#329]
I used the mindflayer bot on my server on version 1.19.2. After updating the server to 1.20.1 (I completely reinstalled Node Js and all npm), the function of specifying motion settings stopped working.
`code:
const defaultMove = new Movements(bot, mcData)
defaultMove.canDig = false
defaultMove.allow1by1towers = false
defaultMove.scafoldingBlocks = [] //mcData.itemsByName.stone.id
bot.pathfinder.setMovements(defaultMove)
bot.pvp.movements = defaultMove;
`

`error:
TypeError: Cannot read properties of undefined (reading 'setMovements')
`

**Comment by Vyacheslav73195** [comment]
At the same time, if you comment out the motion settings function, the bot works and moves properly, but breaks blocks, etc.

**Comment by IceTank** [comment]
Can you show your full code? It looks like the plugin was not loaded when you called setMovements. When using plugins with mineflayer you have to make sure the plugin is loaded before being able to use them.

**Comment by Vyacheslav73195** [comment]
I'm afraid the cat will be too long to upload it here, but the plugin is loaded, there is the above fragment

`
const {pathfinder, Movements, goals: {GoalNear, GoalBlock, GoalFollow}} = require('mineflayer-pathfinder');
bot.loadPlugin(pathfinder);
`

**Comment by IceTank** [comment]
you have to wait for the spawn event before using setMovements

**Comment by Vyacheslav73195** [comment]
Let me describe exactly the order in the code:
declaration
of the spawn bot constant 
Loading the plugin
Setting the settings

**Comment by Vyacheslav73195** [comment]
After all, the most important thing is that this code has been working stably for half a year. I just want to run it at 1.20 instead of 1.19

**Comment by Vyacheslav73195** [comment]
Or do you suggest simply setting the delay to a conditional 5-10 seconds so that the bot will definitely have time to enter the game?

**Comment by Vyacheslav73195** [comment]
oh, moving the application of settings to the end of the "boot.once('spawn'," function really helped. I don't know why it stopped working when updating, but thank you!)
