### ISSUE TITLE
Ability to set a goal for breaking/placing blocks

### ISSUE THREAD

**Issue by Isti01** [PrismarineJS/mineflayer-pathfinder#38]
Adding some kind of block breaking/placing as a goal functionality would be really useful. 
With this feature the bot would have a lot more usecases.

**Comment by Karang** [comment]
With the interact goal proposed in https://github.com/Karang/mineflayer-pathfinder/pull/23 we'll be one step closer to implement this new feature.

**Comment by IceTank** [comment]
Added by https://github.com/PrismarineJS/mineflayer-pathfinder/commit/f9b50611b5d0e68b087d9b292d6f7462d72196bc and https://github.com/PrismarineJS/mineflayer-pathfinder/pull/198
