### ISSUE TITLE
Event listener leak

### ISSUE THREAD

**Issue by ph0t0shop** [PrismarineJS/mineflayer-pathfinder#81]
So, this is actually only after the mineflayer promisification update, so it's not entirely mineflayer-pathfinder's fault, but let me explain:

Mineflayer-pathfinder uses `bot.look` and `bot.lookAt`. These are actually both asynchronous functions with a callback, but mineflayer uses them in a synchronous way. This is actually relying on a quirk of mineflayer that it had in the previous version and not proper behavior. Because it also didn't use the force parameter. Let's look at the `bot.look` function in the previous version:

```
bot.look = (yaw, pitch, force, cb) => {
    bot.entity.yaw = yaw
    bot.entity.pitch = pitch
    if (force) {
      lastSentYaw = yaw
      lookAtCb = noop
      cb()
    } else {
      lookAtCb = cb || noop
    }
  }
```
And let's look how mineflayer-pathfinder uses it:
```
// run toward next point
    bot.look(Math.atan2(-dx, -dz), 0)

    const lx = -Math.sin(bot.entity.yaw)
    const lz = -Math.cos(bot.entity.yaw)

    const frontBackProj = lx * dx + lz * dz
    bot.setControlState('forward', frontBackProj > 0)
    bot.setControlState('back', frontBackProj < 0)
```

As you can see, there's also no _force_ parameter used. So it just starts the looking process and starts walking. But also, `bot.look` can be called in very quick succession. For this to make sense, you'd expect at least the force parameter to be set to _true_, so that it immediately returns and doesn't mess with the lookAtCb (which, by itself, is a weird construction IMO).

Now, in the promisified version, things have changed. The lookAtCb construction is removed, and it's actually an async function that waits for the exit condition. This means that when calling it as often as mineflayer-pathfinder does, without waiting, it will keep adding event listeners instead of overwriting the lookAtCb function. This is the quirk I was talking about. This causes event listener leakage. In short, what I'm trying to say is: the _force_ parameter should, in my opinion, be set to true on both calls to `bot.look` and `bot.lookAt`, to fix this issue. Let me know if you disagree with any of my reasoning.

**Comment by Karang** [comment]
We'll have to think about it, but we cannot afford to wait for the look to complete, and we don't want to force it either.

Let me explain a bit. The bot has 2 yaw values:
* the internal one `bot.entity.yaw` that is always updated instantly (sync) and that is used for most internal computation including physic
* the external one `lastSentYaw` which is the yaw visible by the server and other players: it follow the internal yaw with a delay so the head don't appear to be snapping around
Using the callback only ensure the `lastSentYaw` as reached the value of `bot.entity.yaw` which for application like digging where the server need to know the actual yaw for line of sight checking is important, but for physic that is computed client side, it adds unnecessary delay.

The clean solution IMO would be to add a sync version of `look` and `lookAt`

**Comment by ph0t0shop** [comment]
But the way it was before was basically already implicitly forcing it (by relying on a quirk), and `force` should have been true all along. Now this error is exposed due to the promisification of mineflayer.

**Comment by ph0t0shop** [comment]
Ah well I see what you mean, it wasn't really forcing it but the behavior before was pretty weird still. I think your suggestion of having a sync `look` and `lookAt` is pretty good.

**Comment by Karang** [comment]
How was it weird?
`force` is `undefined`, so it goes in the else and `lookAtCb` default to `noop`

**Comment by ph0t0shop** [comment]
You're right. I was more referring to the behavior of the `lookAt` function, since it does stuff both synchronously and asynchronously. I guess this is just an artifact of that behavior, and now that it's an asynchronous function there's really no good way to use it like before. So indeed, adding sync versions is probably the best solution
