### ISSUE TITLE
Do not interfere with the operation of setControlState.

### ISSUE THREAD

**Issue by nusu-github** [PrismarineJS/mineflayer-pathfinder#87]
After updating to Release 1.2.0, I can no longer move with setControlState.

**Comment by nusu-github** [comment]
![2020-12-15_06 27 37](https://user-images.githubusercontent.com/29514220/102137915-ec96e900-3e9e-11eb-8f01-5edba2bff8ac.png)

`
bot.on("move", () => {
  const target = nearestEntity(bot, "player", 2);
  if (target) {
    bot.lookAt(target.position.offset(0, target.height, 0));
    bot.setControlState("sprint", false);
    bot.setControlState("back", true);
    bot.setControlState("left", true);
  } else {
    bot.setControlState("sprint", true);
    bot.setControlState("back", false);
    bot.setControlState("left", false);
  }
});
`

**Comment by Karang** [comment]
Thanks for the report, should be fixed now. I'll release a minor version.
