### ISSUE TITLE
The value of thinkTimeout is not reflected.

### ISSUE THREAD

**Issue by nusu-github** [PrismarineJS/mineflayer-pathfinder#88]
bot.once("spawn", () => {
  const mcData = require("minecraft-data")(bot.version);
  defaultMove = new Movements(bot, mcData);
  defaultMove.canDig = false;
  defaultMove.maxDropDown = 64;
  bot.pathfinder.thinkTimeout = 50000
});

{
  status: 'timeout',
  cost: 43.79898987322333,
  time: 40.028299999888986,
  visitedNodes: 865,
  generatedNodes: 961,
  path: [...]
}

**Comment by Karang** [comment]
Yes this is the new behavior. The tick timeout is always 40, but the bot will continue to think on next ticks until thinkTimeout is exhausted.

**Comment by nusu-github** [comment]
Can you add an option to change the tick timeout directly?
My programming may be bad, but if the tick timeout is too short, the bot can't get to high places.

**Comment by Karang** [comment]
It will have the same computing time as before, it will just start walking sooner.

**Comment by Karang** [comment]
I changed the status to `partial` to reflect that the computation isn't really done and will continue next tick. And I updated the api: https://github.com/PrismarineJS/mineflayer-pathfinder#path_update
I hope its a bit more intuitive now

**Comment by nusu-github** [comment]
The BOT now runs more smoothly.
Thank you very much.
