### ISSUE TITLE
Breaks block but the server doesn't register

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#96]
Hello,
the bot very often when strip mining (mostly at head level) tries to mine the block in front, but somehow server-side fails and then tries to run into the wall.

Serverside the bot just stays there but viewing it with the prismarine viewer, it actually tries to walk through it and on the viewer the block is not even there.

I only tried this on 1.16.4

Thanks for your awesome module!

**Comment by Karang** [comment]
This seems to be a mineflayer issue. Open an issue at https://github.com/PrismarineJS/mineflayer/issues with all the details required.
