### ISSUE TITLE
Parkour 3 blocks one up fail

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#97]
Hello,
basically every time the bot encounters a 3 block wide gap with the target block being one up, they straigt up die from fall damage after time and never make it.

I don't know if this has to do with the momentum, because they turn around really fast and try the jump, here is a picture non the less:

![image](https://user-images.githubusercontent.com/43215895/103961224-50d26300-5154-11eb-9569-54e202f57a0e.png)

I am rocking these bots on the newest version of every module and Minecraft Vanilla Server 1.16.4

**Comment by Karang** [comment]
Even with the just released 1.3.0 ?
![image](https://user-images.githubusercontent.com/1977472/103961575-0dc4bf80-5155-11eb-98e4-9f9bf480ad2d.png)

**Comment by SinanAkkoyun** [comment]
You know what, thank you very much! I just updated and they almost scare me with their precision and determination! >:)

I love this, thanks for your work!
