### ISSUE TITLE
Bots sometimes need to be hit in order for them to take the path they want?

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer-pathfinder#99]
I don't know what is going on and if this happens to only one bot, but when I run 10 bot instances on a 1.16.4 vanilla server, sometimes they just stop and don't move to the target unless I hit them?

Very strange

**Comment by Karang** [comment]
I don't know if its related but I fixed a bug in the jump prediction that could cause the bot to stop if it couldn't predict a successful jump. Try with 1.3.2
